import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from "./provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "CONNECTO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="/icon.jpg" sizes="192x192" />
      </head>
      <body className={inter.className} >
      <NextAuthSessionProvider>
        <div className="mx-6 md:mx-16">
          <Header/>
          <Toaster />
          {children}  
        </div>
      </NextAuthSessionProvider>
      </body>
    </html>
  );
}
